[package]
name = "rsbkb"
version = "0.5.0"
authors = ["Raphaël Rigo <devel@syscall.eu>"]
edition = "2018"

[dependencies]
hex = "0.3.2"
base64 = "0.10.1"
percent-encoding = "2.1.0"
clap = "2.33.0"
crc = "1.8.1"
atty = "0.2"

[[bin]]
name = "rsbkb"
path = "src/main.rs"
