[package]
name = "rsbkb"
version = "0.9.0"
authors = ["Raphaël Rigo <devel@syscall.eu>"]
edition = "2018"

[dependencies]
hex = "0.3.2"
base64 = "0.13"
percent-encoding = "2.1.0"
clap = "2.33.0"
crc = "2"
atty = "0.2"
time = {version = "0.3", features=["local-offset", "formatting"]}
regex = "1.5"
memmap2 = "0.5"

[[bin]]
name = "rsbkb"
path = "src/main.rs"
