name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose --release
    - uses: actions/upload-artifact@v2
      with:
        name: rsbkb-linux64-${{ github.sha }}
        path: target/release/rsbkb

